# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfd8e5a102c8fd7991d9540bea6591c698ef5f681ae0bf433a03bb14991b5f0b2ba5a5a206d7ceb974eee97a72c20607d5a84ade0cd70300cd5b0a875f115e02

test:
  secret_key_base: 1efc71609371864d97abcc20229b37f85831b5671414b996dd5c286b05cae37445d137aad7f530c414e2cda508fae5405f0f8555d6c2194f98c9f02a867234ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
